language: objective-c
osx_image: xcode9

before_install:
  - gem install cocoapods -v '1.3.1'
  - pod repo update

after_success:
  - bash <(curl -s https://test.duckbuild.io/ci/travis/scripts/upload)
